// Generated by https://quicktype.io

import type { IconType } from "ant-design-vue/lib/vc-tree/interface"

export interface Product {
  id: number
  name: string
  image: string
  price: number
  stock: number
  createdAt: string
  updatedAt: string
}

export interface StockCardInterface {
  title: string
  amount: number
  icon: IconType
  color: string
}